# Project: WordCount
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = WordCount.o
LINKOBJ  = WordCount.o
LIBS     = -L"D:/Dev-C++/Dev-Cpp/MinGW64/lib" -L"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WordCount.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

WordCount.o: WordCount.c
	$(CC) -c WordCount.c -o WordCount.o $(CFLAGS)
